name: Build & Notify

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      #      - name: Install dependencies
#        run: npm ci

      - name: Install and Build (inside ui-kit)
        run: |
          cd docs
          npm install
          npm run build-doc

      - name: Ensure dist directory exists
        run: mkdir -p ui/docs/dist

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui docs keep dist
          path: ui/docs/dist
#      - name: Build project
#        run: npm run build

#      - name: Notify lite-u.github.io
#        uses: peter-evans/repository-dispatch@v3
#        with:
#          token: ${{ secrets.GH_PAT }}
#          repository: lite-u/lite-u.github.io
#          event-type: update-dist
#          client-payload: '{"source":"lite-u/ui"}'