name: Build & Notify

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

#      - name: Notify lite-u.github.io
#        uses: peter-evans/repository-dispatch@v3
#        with:
#          token: ${{ secrets.GH_PAT }}
#          repository: lite-u/lite-u.github.io
#          event-type: update-dist
#          client-payload: '{"source":"lite-u/ui"}'